require("./corestuff/mysql");
require("./commands/clothes");
require("./commands/misc");
require("./commands/teleport");
require("./commands/weapons");
require("./commands/faction")
require("./events/joinevents");
require("./events/playerdeath");
require("./events/despawn");
require("./events/leaveevents");
require("./events/teams");
require("./events/menuquanao");
require("./events/chitay");
require("./events/playerchat");
require("./scripts/ffa");
require("./scripts/garage");
require("./scripts/healing");
require("./scripts/vukhi");
require("./scripts/hanhdong");